name: 'Openstack Kube Image Builder'
description: 'Uses an Openstack cloud to build images for Kubernetes using the eschercloudai/image-builder repo.'
branding:
  icon: layers
  color: purple
inputs:
  os-auth-url:
    description: "The authentication endpoint of OpenStack to send requests to."
    required: true
  os-username:
    description: "The username to authenticate with - required if not using application credentials."
    required: false
  os-password:
    description: "The password to authenticate with - required if not using application credentials."
    required: false
  os-application-credential-id:
    description: "The application credential id to authenticate with - required if not using username/password combination."
    required: false
  os-application-credential-secret:
    description: "The application credential secret to authenticate with - required if not using username/password combination."
    required: false
  os-project-name:
    description: "The name of the Openstack project."
    required: true
  os-project-id:
    description: "The ID of the Openstack project."
    required: true
  os-project-domain-name:
    description: "The name of the ProjectDomainName. Default: \"default\"."
    required: false
    default: "default"
  os-user-domain-name:
    description: "The name of the UserDomainName. Default: \"Default\"."
    required: false
    default: "Default"
  os-region-name:
    description: "The name of the region to deploy to. Default: \"RegionOne\"."
    required: false
    default: "RegionOne"
# TODO:  confirm if this is needed
#  os-auth-plugin:
#    description: 'The auth plugin type that Openstack will use.'
#    required: false
#    default: "password"
  os-identity-api-version:
    description: "The Identity API Version for Openstack. Default: \"3\"."
    required: false
    default: "3"
  os-interface:
    description: "The name of the interface. Default: \"public\"."
    required: false
    default: "public"
  network-id:
    description: "The ID of the network to use to use to build the scanning system."
    required: true
  attach-config-drive:
    description: "Whether to enable to config drive in Openstack. Useful if building an instance with an external IP attached. Default: \"false\"."
    required: false
    default: "false"
  image-repo:
    description: "The to use for building Kubernetes images. Default: \"https://github.com/eschercloudai/image-builder.git\"."
    required: false
    default: "https://github.com/eschercloudai/image-builder.git"
  build-os:
    description: "The OS to build. Currently supports ubuntu-2004 and ubuntu-2204. Default: \"ubuntu-2204\"."
    required: false
    default: "ubuntu-2204"
  source-image-id:
    description: "The ID of the source image to use for the image build."
    required: true
  flavor-name:
    description: "The Openstack instance flavor to use to build the image."
    required: true
  use-floating-ip:
    description: "Enable to use floating IPs on the build instance. Default: \"true\"."
    required: false
    default: "true"
  floating-ip-network-name:
    description: "If using a floating IP configuration, add the network name here to which the floating IP will be acquired from. (Usually the provider network). Default: \"Internet\"."
    required: false
    default: "Internet"
  image-visibility:
    description: "Set the image visibility once it has been created. Usually required admin permissions of sorts. Ensure you have this before setting this as the whole process will fail if permissions are not set. Default: \"private\"."
    required: false
    default: "private"
  crictl-version:
    description: 'The crictl version to deploy into the image. Default: \"1.25.\".'
    required: false
    default: "1.25.0"
  k8s-version:
    description: 'The Kubernetes version to deploy into the image. Default: \"1.25.3\".'
    required: false
    default: "1.25.3"
  enable-nvidia-support:
    description: "Set to enable Nvidia support. You must have valid a license and location to install the .run file from to use this. You'll also need an instance with a GPU added to build the GPU drivers. Default: \"false\"."
    required: false
    default: "false"
  nvidia-installer-url:
    description: "The URL from which you will pull your installer file. You need to supply this if enabling GPU support."
    required: false
    default: ""
  nvidia-driver-version:
    description: "the NVIDIA Driver version you are installing. This is currently only used to set the image name. Default: \"510.7308\"."
    required: false
    default: "510.73.08"
  grid-license-server:
    description: "The server url/ip from which the grid license can be acquired."
    required: false
    default: ""
  gh-token:
    description: "The GitHub project token to which the results can be pushed to for a GitHub Pages support."
    required: true
  gh-pages-branch:
    description: "The branch in which the results should be pushed. Default: \"gh-pages\"."
    required: false
    default: "gh-pages"
runs:
  using: "composite"
  steps:
    - name: "Setup the clouds.yaml file"
      id: prepare_cloud
      shell: bash
      run: |
        mkdir -p ~/.config/openstack/
        export APP_CRED_ID=${{ inputs.os-application-credential-id }}
        export APP_CRED_SECRET=${{ inputs.os-application-credential-secret }}
        
        if [[ -z $APP_CRED_ID ]] || [[ -z $APP_CRED_SECRET ]]; then
          cat <<-EOF > ~/.config/openstack/clouds.yaml
          clouds:
            openstack:
              auth:
                auth_url: ${{ inputs.os-auth-url }}
                username: ${{ inputs.os-username }}
                password: ${{ inputs.os-password }}
                project_id: ${{ inputs.os-project-id }}
                project_name: ${{ inputs.os-project-name }}
                user_domain_name: ${{ inputs.os-user-domain-name }}
              region_name: "${{ inputs.os-region-name }}"
              interface: " ${{ inputs.os-interface }}"
              identity_api_version:  ${{ inputs.os-identity-api-version }}
        EOF
        else
          cat <<-EOF > ~/.config/openstack/clouds.yaml
          clouds:
            openstack:
              auth:
                auth_url: ${{ inputs.os-auth-url }}
                application_credential_id: ${{ inputs.os-application-credential-id }}
                application_credential_secret: ${{ inputs.os-application-credential-secret }}
              region_name: "${{ inputs.os-region-name }}"
              interface: " ${{ inputs.os-interface }}"
              identity_api_version:  ${{ inputs.os-identity-api-version }}
              auth_type: "v3applicationcredential"
        EOF
        fi
    - name: "Fetch Baskio"
      if: runner.os == 'Linux'
      id: fetch_baskio
      env:
        BASKIO_VERSION: "v0.0.3-beta.2"
      run: |
        wget -q https://github.com/eschercloudai/baskio/releases/download/${BASKIO_VERSION}/baskio-linux-amd64 -O baskio
        chmod +x baskio
      shell: bash
    - name: "Build Image"
      if: runner.os == 'Linux'
      id: build
      run: |
        cat <<-EOF > /tmp/baskio-config.yaml
        clouds-file: "~/.config/openstack/clouds.yaml"
        cloud-name: "openstack"
        build:
          build-os: "${{ inputs.build-os }}"
          attach-config-drive: ${{ inputs.attach-config-drive }}
          image-repo:  ${{ inputs.image-repo }}
          network-id: "${{ inputs.network-id }}"
          source-image: "${{ inputs.source-image-id }}"
          flavor-name: "${{ inputs.flavor-name }}"
          use-floating-ip: ${{ inputs.use-floating-ip }}
          floating-ip-network-name: "${{ inputs.floating-ip-network-name }}"
          image-visibility: "${{ inputs.image-visibility }}"
          crictl-version: "${{ inputs.crictl-version }}"
          kubernetes-version: "${{ inputs.k8s-version }}"
          enable-nvidia-support: ${{ inputs.enable-nvidia-support }}
          nvidia-installer-url: "${{ inputs.nvidia-installer-url }}"
          nvidia-driver-version: "${{ inputs.nvidia-driver-version }}"
          grid-license-server: "${{ inputs.grid-license-server }}"
        EOF
        ./baskio build --baskio-config /tmp/baskio-config.yaml
        echo "new-image-id=$(cat /tmp/imgid.out)" >> $GITHUB_OUTPUT
      shell: bash
    - name: "Scan Image"
      if: runner.os == 'Linux'
      id: scan
      run: |
        cat <<-EOF > /tmp/baskio-config.yaml
        clouds-file: "~/.config/openstack/clouds.yaml"
        cloud-name: "openstack"
        scan:
          image-id: "f54a5c29-6b46-47d2-97d4-3c1148be418e"
          #image-id: "${{ steps.build.outputs.new-image-id }}"
          flavor-name: "${{ inputs.flavor-name }}"
          network-id: "${{ inputs.network-id }}"
          attach-config-drive: ${{ inputs.attach-config-drive }}
        EOF
        ./baskio scan --baskio-config /tmp/baskio-config.yaml
      shell: bash
    - name: "Publish Image"
      if: runner.os == 'Linux'
      id: publish
      run: |
        cat <<-EOF > /tmp/baskio-config.yaml
        clouds-file: "~/.config/openstack/clouds.yaml"
        cloud-name: "openstack"
        publish:
          #image-id: "${{ steps.build.outputs.new-image-id }}"
          image-id: "f54a5c29-6b46-47d2-97d4-3c1148be418e"
          github:
            user: $(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
            project: $(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")
            token: "${{ inputs.gh-token }}"
            pages-branch: "${{ inputs.gh-pages-branch }}"
        EOF
        ./baskio publish --baskio-config /tmp/baskio-config.yaml
      shell: bash